trigger:
  - master

pool:
  name: 'slave-node'

steps:
  # Step 1: Check out the source code from the repository
  - script: |
      echo "Checkout from azure repo"
  - checkout: self
    persistCredentials: true

  # Step 2: Display the actual agent name
  - script: |
      echo "Running on agent: $(Agent.Name)"
    displayName: 'Display Agent Name'

  # Step 3: Build the Docker image
  - script: |
      echo "Build Docker Images"
      docker build -t flask-app:$(Build.BuildId) .
    displayName: 'Build Docker Image'

  # Step 4: Deploy the Docker container using the pool agent
  - script: |
      echo "Deploying the container on Docker host"
      docker rm -f flask-app || true  # Remove the container if it exists
      docker run -dit --name flask-app -p 8081:80 flask-app:$(Build.BuildId)
    displayName: 'Deploy Docker Container'
