trigger:
  - master

pool:
  name: 'slave-node'

steps:
  # Step 1: Check out the source code from the repository
  - script: |
      echo "Checkout from azure repo"
  - checkout: self

  # Step 2: Display the actual agent name
  - script: |
      echo "Running on agent: $(Agent.Name)"
    displayName: 'Display Agent Name'

  # Step 3: Build the Docker image
  - script: |
      echo "Build Docker Images"
      cp Dockerfile Admin/
      sudo docker build -t my-angular-app:$(Build.BuildId) Admin/
      sudo docker tag my-angular-app:$(Build.BuildId) 769916001201.dkr.ecr.ap-south-1.amazonaws.com/visionapplycrm:latest
    displayName: 'Build Docker Image'

  # Step 4: "Push Docker Image to AWS ECR"
  - script: |
      echo "Push Docker Image"
      sudo docker push 769916001201.dkr.ecr.ap-south-1.amazonaws.com/visionapplycrm:latest
    displayName: 'Push Docker Image to AWS ECR'

  # Step 5: Deploy the Docker container DEV
  - script: |
      echo "Deploying to DEV"
      sudo docker rm -f my-angular-app
      sudo docker run -dit --name my-angular-app -p 4300:80 769916001201.dkr.ecr.ap-south-1.amazonaws.com/visionapplycrm:latest
    displayName: 'Deploy to DEV'
