## deployment.yml ##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionapply-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: frontend-app
        image: 650378210006.dkr.ecr.ap-south-1.amazonaws.com/visionapply-frontend-prod:6035
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
## svc.yml ##
apiVersion: v1
kind: Service
metadata:
  name: visionapply-frontend
  labels:
    app: visionapply-frontend
spec:
  selector:
    env: prod
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      
## ingress.yml##

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visionapply-frontend-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: "alb-visionway-eks"
    alb.ingress.kubernetes.io/load-balancer-name: "alb-visionway-eks"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/target-type: ip

spec:
  tls:
  - hosts:
      - visionway.visionapply.com
      - vision.visionapply.com
  ingressClassName: alb-ingress
  rules:
    - host: "visionway.visionapply.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visionapply-frontend
                port:
                  number: 80
    - host: "vision.visionapply.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visionapply-frontend
                port:
                  number: 80

